services:
  nginx:
    build: ./requirements/nginx
    image: nginx:ayel-mou
    container_name: nginx
    ports:
      - "443:443"
    restart: always 
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - volume_wordpress:/var/www/wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:ayel-mou
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: always 
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - user_and_passowrd
    volumes:
      - volume_wordpress:/var/www/wordpress
      
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:ayel-mou
    container_name: mariadb
    restart: always 
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - volume_mariadb:/var/lib/mysql
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:ayel-mou
    container_name: adminer
    ports:
      - "8083:8083"
    restart: always 
    networks:
      - inception
  redis:
    build: ./requirements/bonus/redis
    image: redis:ayel-mou
    container_name: redis
    restart: always
    networks:
      - inception
    volumes:
      - redis-data:/data
  site:
    build: ./requirements/bonus/myresume
    image: myresume:ayel-mou
    container_name: myresume
    ports:
      - "4242:4242"
    restart: always 
    networks:
      - inception
    volumes:
      - ./requirements/bonus/myresume/site:/var/www/html/
  jupyter:
    build: ./requirements/bonus/jupyter
    image: jupyter:ayel-mou
    container_name: jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      - inception
    volumes:
      - ./requirements/bonus/jupyter/src:/workspace/srcs
    working_dir: /workspace/srcs

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:ayel-mou
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env 
    volumes:

      - volume_wordpress:/var/www/wordpress

networks:
  inception:
    driver: bridge
    name: inception
    
volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ayel-mou/data/mariadb
  volume_wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ayel-mou/data/wordpress
  redis-data: {} 


secrets:
  db_password:
    file: ../secrets/db_password.txt
  user_and_passowrd:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt